# RGX build entrypoint — ONE command builds RGX and all its dependencies,
# hiding the PGEN regex-parser bootstrap. From a cold clone (or when RGX is
# itself a git submodule), just run:
#
#     make            # = make build
#
# Why this exists: RGX's parser is generated by PGEN (vendored as the
# `subs/pgen` submodule). Since PGEN commit 0ed2b2ad the generated parser
# (`subs/pgen/generated/*`) is no longer tracked (too large to vendor), so a
# fresh checkout has no parser and a plain `cargo build` fails with a cryptic
# "couldn't read .../generated/return_annotation_parser.rs". This Makefile runs
# the one-time bootstrap for you. It is idempotent — re-running is a no-op once
# the parser is generated. See docs/decisions/0002 and the README "Building".
#
# (True zero-step `cargo build` would require PGEN's own crate to self-bootstrap
# via its build.rs; RGX can't add that — `subs/pgen` is read-only here.)

SHELL := /bin/bash
CARGO ?= cargo
PGEN_RUST := subs/pgen/rust
PGEN_GENERATED := subs/pgen/generated

.PHONY: build bootstrap submodules test gate clean help
.DEFAULT_GOAL := build

build: bootstrap ## Bootstrap PGEN (if needed) then build the workspace
	$(CARGO) build

bootstrap: submodules ## Generate PGEN's parser if missing (one-time, idempotent)
	@if [ -f "$(PGEN_GENERATED)/regex_parser.rs" ] && [ -f "$(PGEN_GENERATED)/return_annotation_parser.rs" ]; then \
	  echo "[rgx] PGEN parser already generated — nothing to bootstrap."; \
	else \
	  echo "[rgx] Generating the PGEN regex parser (one-time bootstrap)..."; \
	  $(MAKE) -C "$(PGEN_RUST)" SHELL=/bin/bash regex_parser_bootstrap; \
	fi

submodules: ## Ensure the pinned PGEN submodule is checked out (build dependency)
	@if [ ! -f "$(PGEN_RUST)/Cargo.toml" ]; then \
	  echo "[rgx] Initializing the subs/pgen submodule..."; \
	  git submodule update --init --recursive subs/pgen; \
	fi

test: bootstrap ## Bootstrap then run the rgx-core test suite
	$(CARGO) test -p rgx-core

gate: bootstrap ## Bootstrap then run the full local CI gate (the merge gate)
	./scripts/run-local-ci.sh

clean: ## Remove cargo build artifacts (keeps the generated PGEN parser)
	$(CARGO) clean

help: ## Show available targets
	@echo "RGX build targets:"; \
	grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
	  | awk 'BEGIN{FS=":.*?## "}{printf "  make %-11s %s\n", $$1, $$2}'
