use rgx_core::ast::*;
use rgx_core::vm::*;

fn main() {
    let mut compiler = OptimizingCompiler::new();

    // Create alternation AST: cat|dog
    let ast = Regex::Alternation(vec![
        Regex::Sequence(vec![Regex::Char('c'), Regex::Char('a'), Regex::Char('t')]),
        Regex::Sequence(vec![Regex::Char('d'), Regex::Char('o'), Regex::Char('g')]),
    ]);

    let program = compiler.compile(&ast);

    println!("Generated bytecode:");
    for (i, byte) in program.code.iter().enumerate() {
        println!(
            "{:3}: 0x{:02X} ({:3}) {}",
            i,
            byte,
            byte,
            if let Ok(op) = OpCode::try_from(*byte) {
                format!("{op:?}")
            } else {
                "Data".to_string()
            }
        );
    }

    println!("\nTesting VM:");
    let vm = RegexVM::new(program);

    println!("is_match('cat'): {}", vm.is_match("cat"));
    println!("is_match('dog'): {}", vm.is_match("dog"));
    println!("is_match('bird'): {}", vm.is_match("bird"));
}
