use rgx_core::ast::*;
use rgx_core::vm::*;

fn main() {
    let mut compiler = OptimizingCompiler::new();

    // Simple single character pattern
    let ast = Regex::Char('c');
    let program = compiler.compile(&ast);

    println!("Testing character 'c' encoding:");

    // Test the encoding manually
    let ch = 'c';
    let mut buf = [0; 4];
    let utf8_str = ch.encode_utf8(&mut buf);
    let utf8_bytes = utf8_str.as_bytes();

    println!("Character: {}", ch);
    println!("UTF-8 string: {:?}", utf8_str);
    println!("UTF-8 bytes: {:?}", utf8_bytes);
    println!("Length: {}", utf8_bytes.len());

    println!("\nGenerated bytecode:");
    for (i, byte) in program.code.iter().enumerate() {
        println!(
            "{:3}: 0x{:02X} ({:3}) {}",
            i,
            byte,
            byte,
            if let Ok(op) = OpCode::try_from(*byte) {
                format!("{:?}", op)
            } else {
                format!("Data")
            }
        );
    }

    println!("\nTesting VM:");
    let vm = RegexVM::new(program);

    println!("is_match('c'): {}", vm.is_match("c"));
    println!("is_match('a'): {}", vm.is_match("a"));
    println!("is_match('abc'): {}", vm.is_match("abc"));
}
