/*
 * rgx — high-performance, programmable regex engine.
 *
 * This header is auto-generated by cbindgen from rgx-capi/src/lib.rs.
 * Do not edit by hand. Regenerate via `cargo build -p rgx-capi`.
 *
 * ABI stability: function signatures, error codes, and `#[repr(C)]`
 * struct layouts are stable within a major version. Opaque pointer
 * internals are not — never depend on the size or layout of any
 * `Rgx*` type.
 *
 * See docs/A9_LANGUAGE_BINDINGS_DESIGN.md for the full design.
 */


#ifndef RGX_H
#define RGX_H

#pragma once

/* Generated with cbindgen:0.27.0 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * An unexpected panic from the Rust engine; the panic message is
 * retrievable via [`rgx_last_error`]. Indicates a bug — please
 * report.
 */
#define RGX_ERR_INTERNAL -99

/**
 * A handle was passed to a function that doesn't accept it
 * (e.g. wrong handle type).
 */
#define RGX_ERR_INVALID_HANDLE -7

/**
 * The pattern failed to compile. Call [`rgx_last_error`] for the
 * human-readable diagnostic.
 */
#define RGX_ERR_INVALID_PATTERN -2

/**
 * A text input contained invalid UTF-8 when the API contract
 * required UTF-8. Phase 1 doesn't expose this path (every text
 * API treats inputs as raw bytes); reserved for the eventual
 * `bytes::Regex` distinction.
 */
#define RGX_ERR_INVALID_UTF8 -3

/**
 * A safety limit was exceeded during the match attempt
 * (`max_steps` / `max_backtrack_frames` / `max_recursion_depth` /
 * `max_trail_entries`). Reserved for Phase 3; Phase 1 currently
 * never returns this.
 */
#define RGX_ERR_LIMIT_EXCEEDED -5

/**
 * A required pointer argument was null.
 */
#define RGX_ERR_NULL_POINTER -1

/**
 * Operation succeeded.
 */
#define RGX_OK 0

/**
 * Opaque handle to a compiled regex. Created by [`rgx_compile`];
 * destroyed by [`rgx_regex_free`]; refcounted by
 * [`rgx_regex_retain`].
 *
 * `#[repr(C)]` here is irrelevant because we never expose the
 * fields — the C side only ever holds a `RgxRegex*` (opaque
 * pointer). The pointer is the API contract.
 */
typedef struct RgxRegex RgxRegex;

/**
 * Compile a pattern into an [`RgxRegex`] handle.
 *
 * `pattern` / `pattern_len` describe the pattern as raw bytes
 * (PCRE2-syntax UTF-8 by convention). `out_regex` receives the
 * newly-allocated handle on success.
 *
 * # Returns
 *
 * - [`RGX_OK`] on success; `*out_regex` is populated with a non-
 *   null `RgxRegex*` that the caller must eventually free via
 *   [`rgx_regex_free`].
 * - [`RGX_ERR_NULL_POINTER`] if `pattern` or `out_regex` is null.
 * - [`RGX_ERR_INVALID_PATTERN`] if the pattern fails to compile;
 *   the diagnostic is in [`rgx_last_error`].
 * - [`RGX_ERR_INTERNAL`] on an unexpected panic.
 *
 * # Safety
 *
 * - `pattern` must point to at least `pattern_len` valid bytes.
 * - `out_regex` must point to a valid, writable `RgxRegex*` slot.
 */
 int32_t rgx_compile(const uint8_t *pattern, uintptr_t pattern_len, struct RgxRegex **out_regex) ;

/**
 * Find the first match of the regex in `text`. On success writes
 * the match span (start, end) byte offsets into `*out_start` /
 * `*out_end`. If no match exists, writes `(0, 0)` and returns
 * [`RGX_OK`] with `*out_matched` set to `0`.
 *
 * # Returns
 *
 * - [`RGX_OK`] on success; `*out_matched`, `*out_start`, `*out_end`
 *   populated. `out_matched == 1` means a match was found; `0`
 *   means no match.
 * - [`RGX_ERR_NULL_POINTER`] if any required pointer is null.
 * - [`RGX_ERR_INVALID_UTF8`] if `text` is not valid UTF-8.
 * - [`RGX_ERR_INTERNAL`] on an unexpected panic.
 *
 * # Safety
 *
 * - `re` must be a valid `RgxRegex*` not yet freed.
 * - `text` must point to at least `text_len` valid bytes (or be
 *   null when `text_len == 0`).
 * - `out_matched`, `out_start`, `out_end` must each point to a
 *   valid, writable slot.
 */

int32_t rgx_find_first(const struct RgxRegex *re,
                       const uint8_t *text,
                       uintptr_t text_len,
                       int32_t *out_matched,
                       uintptr_t *out_start,
                       uintptr_t *out_end)
;

/**
 * Test whether the regex matches anywhere in `text`. Writes
 * `1` to `*out_matched` if a match exists, `0` otherwise.
 *
 * # Returns
 *
 * - [`RGX_OK`] on success; `*out_matched` is populated.
 * - [`RGX_ERR_NULL_POINTER`] if `re`, `text`, or `out_matched` is
 *   null. (`text_len == 0` is allowed: an empty input is matched
 *   against the pattern; some patterns match empty strings.)
 * - [`RGX_ERR_INVALID_UTF8`] if `text` is not valid UTF-8.
 * - [`RGX_ERR_INTERNAL`] on an unexpected panic.
 *
 * # Safety
 *
 * - `re` must be a valid `RgxRegex*` not yet freed.
 * - `text` must point to at least `text_len` valid bytes (unless
 *   `text_len == 0`, in which case `text` may be null or any value).
 * - `out_matched` must point to a valid, writable `int32_t` slot.
 */

int32_t rgx_is_match(const struct RgxRegex *re,
                     const uint8_t *text,
                     uintptr_t text_len,
                     int32_t *out_matched)
;

/**
 * Return the calling thread's most recent error message, or a
 * pointer to an empty string if no error has been recorded since
 * the last successful call.
 *
 * The returned pointer is borrowed from per-thread storage and
 * remains valid until the next rgx_* call on the same thread.
 * Callers MUST NOT free it; callers MUST NOT use it after another
 * rgx_* call on the same thread.
 *
 * # Safety
 *
 * The returned pointer is valid for read only, NUL-terminated,
 * UTF-8 (subject to interior-NUL replacement; see implementation
 * notes).
 */
 const char *rgx_last_error(void) ;

/**
 * Free a regex handle previously returned by [`rgx_compile`] or
 * [`rgx_regex_retain`]. Passing a null pointer is a no-op (mirrors
 * `free()` semantics). Passing the same non-null pointer twice is
 * undefined behaviour.
 *
 * # Safety
 *
 * `re` must be either null or a pointer previously returned by
 * [`rgx_compile`] / [`rgx_regex_retain`] and not yet freed.
 */
 void rgx_regex_free(struct RgxRegex *re) ;

/**
 * Create an additional handle to the same compiled regex. Both
 * handles are independent — each must be freed separately via
 * [`rgx_regex_free`]. The underlying engine is shared (Arc-counted),
 * so retaining is cheap.
 *
 * Useful when handing a regex to a worker thread: the spawning
 * thread retains, hands the new handle to the worker, and each
 * frees independently.
 *
 * Returns null if `re` is null.
 *
 * # Safety
 *
 * `re` must be either null or a valid `RgxRegex*` previously
 * returned by [`rgx_compile`] / [`rgx_regex_retain`] and not yet
 * freed.
 */
 struct RgxRegex *rgx_regex_retain(struct RgxRegex *re) ;

/**
 * Major version of the rgx-capi library at runtime. Pair with
 * [`rgx_runtime_version_minor`] / [`rgx_runtime_version_patch`]
 * for the full `MAJOR.MINOR.PATCH` triple. Callers compile against
 * the `RGX_VERSION_*` constants in the generated header and
 * compare at runtime to detect header/library mismatch.
 */
 uint32_t rgx_runtime_version_major(void) ;

/**
 * Minor version. See [`rgx_runtime_version_major`].
 */
 uint32_t rgx_runtime_version_minor(void) ;

/**
 * Patch version. See [`rgx_runtime_version_major`].
 */
 uint32_t rgx_runtime_version_patch(void) ;

#endif  /* RGX_H */

/* End of generated rgx.h */
