#!/usr/bin/env bash
# rgx-capi header-drift gate — enforces rgx-capi/STABILITY.md §7.
#
# `rgx-capi/include/rgx.h` is committed and machine-generated by
# cbindgen (via rgx-capi/build.rs). Two contract checks:
#
#   1. Regenerate the header and assert the committed copy is
#      byte-identical to a fresh cbindgen run (catches "forgot to
#      commit the regenerated header").
#   2. If the committed header's ABI-meaningful content differs from
#      the header at the merge-base, assert the workspace `version`
#      also differs (catches "changed the ABI without bumping the
#      version").
#
# "ABI-meaningful content" = the header minus the pinned banner
# comment block and the cbindgen tool-version stamp; tool/banner
# churn is not an ABI event, declarations/signatures/constants/
# structs are. The check is intentionally conservative: any other
# header change (including doc comments on declarations) requires a
# version bump — the header is machine-generated, so every content
# change is a deliberate, reviewable event.
set -euo pipefail
repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

header="rgx-capi/include/rgx.h"

# --- Check 1: committed header == fresh regeneration ---------------
# build.rs runs cbindgen and rewrites the committed header in place;
# cbindgen is idempotent, so a clean tree stays clean.
echo "[check-capi-abi] Regenerating $header (cargo build -p rgx-capi)"
cargo build --manifest-path Cargo.toml -p rgx-capi >/dev/null
if ! git diff --quiet -- "$header"; then
  echo "[check-capi-abi] DRIFT: regenerated $header differs from the committed copy." >&2
  echo "  cbindgen output changed but the regenerated header was not committed." >&2
  echo "  Run 'cargo build -p rgx-capi' and commit $header." >&2
  git --no-pager diff -- "$header" >&2 || true
  exit 1
fi
echo "[check-capi-abi] committed header is byte-identical to a fresh cbindgen run."

# --- Check 2: ABI-meaningful change implies a version bump ---------
baseline_ref=""
if git rev-parse --verify --quiet origin/main >/dev/null; then
  baseline_ref="origin/main"
elif git rev-parse --verify --quiet main >/dev/null; then
  baseline_ref="main"
fi
if [ -z "$baseline_ref" ]; then
  echo "[check-capi-abi] No origin/main or main ref — skipping the ABI-vs-version"
  echo "  comparison (check 1 still enforced). Expected only on an initial/"
  echo "  detached checkout."
  exit 0
fi
merge_base="$(git merge-base HEAD "$baseline_ref" 2>/dev/null || true)"
if [ -z "$merge_base" ]; then
  echo "[check-capi-abi] No merge-base with $baseline_ref — skipping ABI-vs-version check."
  exit 0
fi

# stdin: a C header → stdout: ABI-meaningful lines only.
meaningful() {
  awk '
    NR==1 && $0 ~ /^\/\*/ { inbanner=1 }
    inbanner { if ($0 ~ /\*\//) inbanner=0; next }
    /^\/\* Generated with cbindgen:/ { next }
    { print }
  '
}

committed_meaningful="$(meaningful < "$header")"
base_meaningful="$(git show "$merge_base:$header" 2>/dev/null | meaningful || true)"

if [ "$committed_meaningful" = "$base_meaningful" ]; then
  echo "[check-capi-abi] header ABI content unchanged vs $baseline_ref ($merge_base) — OK."
  exit 0
fi

ws_version_at() {
  git show "$1:Cargo.toml" 2>/dev/null | awk -F'"' '
    /^\[workspace\.package\]/ { p = 1 }
    p && /^version[[:space:]]*=/ { print $2; exit }'
}
cur_ver="$(awk -F'"' '
  /^\[workspace\.package\]/ { p = 1 }
  p && /^version[[:space:]]*=/ { print $2; exit }' Cargo.toml)"
base_ver="$(ws_version_at "$merge_base")"

echo "[check-capi-abi] header ABI content changed vs $baseline_ref ($merge_base)."
echo "  workspace version: base=${base_ver:-<none>} current=${cur_ver:-<none>}"
if [ -n "$cur_ver" ] && [ "$cur_ver" != "$base_ver" ]; then
  echo "[check-capi-abi] version was bumped alongside the ABI change — OK."
  exit 0
fi
echo "[check-capi-abi] CONTRACT VIOLATION (STABILITY.md §7): rgx.h ABI content" >&2
echo "  changed without a [workspace.package] version bump. Bump the workspace" >&2
echo "  version in Cargo.toml in the same change, per the rgx-capi ABI contract" >&2
echo "  (rgx-capi/STABILITY.md §7)." >&2
exit 1
